# CI-CD
# Runs on push to master
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependenceis
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      #- run: npm run build --if-present
      - run: npm test
      - run: npm run build

  lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run eslint with reviewdog
          # You may pin to the exact commit or the version.
          # uses: reviewdog/action-eslint@c93d1f8efe07ce3b9b2d186ceaa5cd6ced717633
          uses: reviewdog/action-eslint@v1.0.0
          with:
            # GITHUB_TOKEN.
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # Report level for reviewdog [info,warning,error]
            level: error # optional, default is error
            reporter: github-pr-review
